# Generated by Django 3.1.4 on 2021-01-07 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('rating_codechef', models.CharField(max_length=10)),
                ('rating_codeforces', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=10)),
                ('language', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=10)),
                ('rating', models.CharField(max_length=10)),
                ('links', models.CharField(max_length=10)),
            ],
        ),
    ]
