# Generated by Django 3.1.4 on 2021-01-08 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_ratings_email_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratings',
            name='email_user',
        ),
    ]
