# Generated by Django 3.1.4 on 2021-01-08 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_ratings_email_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ratings',
            old_name='our_rating',
            new_name='leaderboard_rank',
        ),
        migrations.RemoveField(
            model_name='ratings',
            name='rank_codechef',
        ),
        migrations.RemoveField(
            model_name='ratings',
            name='rating_codechef',
        ),
    ]
