# Generated by Django 3.1.4 on 2021-01-08 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210108_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='leaderboard_rank',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='organization',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='rank_codeforces',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='rating_codeforces',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
