# Generated by Django 3.1.4 on 2021-01-09 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210108_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='leaderboard_rank',
            field=models.IntegerField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='rank_codeforces',
            field=models.IntegerField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='rating_codeforces',
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
