# Generated by Django 3.1.5 on 2021-01-10 04:19

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210109_0703'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='ratings',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
