# Generated by Django 3.1.5 on 2021-01-10 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210110_0419'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='ratings',
            managers=[
            ],
        ),
    ]
