# Generated by Django 3.1.5 on 2021-02-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210110_0424'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='links',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='leaderboard_rank',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='rank_codeforces',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='rating_codeforces',
            field=models.IntegerField(null=True),
        ),
    ]
